[phases.setup]
nixPkgs = ['python311', 'gcc']

[phases.install]
cmds = [
    'python -m venv --copies /opt/venv',
    '. /opt/venv/bin/activate && pip install --upgrade pip',
    '. /opt/venv/bin/activate && pip install -r requirements.txt'
]

[phases.build]
cmds = ['python manage.py collectstatic --noinput']

[start]
cmd = 'gunicorn CabinetAvocat.wsgi --bind 0.0.0.0:$PORT'